config/routes.rb
Rails.application.routes.draw do
  
  root 'products#index'
  
  resources :products

  get 'products/:id/menos' => 'products#menos', as: :menos
  get 'products/:id/mais' => 'products#mais', as: :mais

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :menos, :mais]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def menos
    @product.quantity -= 1;
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url }
        format.json { head :no_content }
      else
        format.html { redirect_to products_url, notice: 'Erro!' }
        format.json { head :no_content }
      end
    end
  end

  def mais
    @product.quantity += 1;
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url }
        format.json { head :no_content }
      else
        format.html { redirect_to products_url, notice: 'Erro!' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos de Informática</h1>

<div class="row">


  <div class="col-xs-6">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th></th>
          <th>Quantity</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        
        <% @products.order(:name).each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>

            <td><%= link_to '-', menos_url(product) %></td>
            <td><%= product.quantity %></td>
            <td><%= link_to '+', mais_url(product) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>



  <!-- Line Chart - Single Series 
  <div class="col-xs-6">
    <h3>Produtos por quantidade</h3>
    <%= line_chart @products.group(:quantity).count %>
  </div>-->

   <!-- Pie Chart -->
  <div class="col-xs-6">
    <h3>Produtos por quantidade</h3>
    <%= pie_chart @products.group(:name).sum(:quantity) %>
  </div>
</div>

<div class="row">
  <!-- Column Chart --> 
  <div class="col-xs-6">
    <h3>Produtos x Preços</h3>
    <%= column_chart @products.group(:name).sum(:price) %>
  </div>
  <!-- Bar Chart --> 
  <div class="col-xs-6">
    <h3>Produtos x Preços</h3>
    <%= bar_chart @products.group(:name).sum(:price) %>
  </div>
</div>



<br>



  
 

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>